### ISSUE TITLE
Consider making LockLayer qukeys

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-Qukeys#22]
In the keymap, Qukeys could (optionally) treat `LockLayer(N)` as an automatic Qukey, with an alternate keycode of `ShifToLayer(N)`

**Comment by gedankenexperimenter** [comment]
This could work on `ShiftToLayer()` keys, too.

**Comment by jamadagni** [comment]
This is functionally identical to sticky one shot layer except for number of presses required for locking.

**Comment by gedankenexperimenter** [comment]
Yes, it would be functionally very similar to OneShot, which is one reason I probably won't implement it. The main difference would be speed of use.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#398.
