### ISSUE TITLE
Add double-tap & hold for primary keycode repeat

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-Qukeys#29]
See keyboardio/Kaleidoscope-DualUse#8

**Comment by gedankenexperimenter** [comment]
This would work for the typical use case, where someone wants repeated characters, but not for the macOS Cocoa input for non-ASCII characters, because we'd get an extra normal character before the hold took effect.

This could be solved by not sending the report for the key release until after a timeout where the qukey was the last key in the queue. If it gets pressed again (before any other keypress events), it becomes a hold, with no release. If it times out, or another key is pressed, the release gets sent.

This would require only one set of values to be stored. One timeout constant, one start time, and one key addr should be sufficient.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#399.
