### ISSUE TITLE
Rewrite documentation

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-Qukeys#39]
The current documentation is very poor. It needs to be updated for recent feature changes, and to have examples for various use cases:

- Qukey definition
- DualUse definition
- release delay usage
- long-press usage

et cetera…

**Comment by gedankenexperimenter** [comment]
- mod / printable usage
- layer shift / printable usage
- layer shift / layer lock usage
- Macros & OneShot interactions

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#400.
