### ISSUE TITLE
Generic alternative to LT and MT

### ISSUE THREAD

**Issue by noctuid** [keyboardio/Kaleidoscope-Qukeys#42]
I'd prefer to define qukeys directly in the keymap but would also prefer to use a more consistent interface if possible. It would be nice if there was a generic macro that could cover both keys and functions (e.g. it could replace both `Qukey(x, x, x, Key_ModifierName)` and `Qukey(x, x, x, ShiftToLayer(...))`).

**Comment by gedankenexperimenter** [comment]
I'm not sure what you're getting at here. The only way to define Qukeys in the keymap is with the DualUse macros (`LT`/`MT`). The full `Qukey` definitions, with layer, row, & column coordinates can't really get any more consistent; the last parameter is any `Key` object that can be defined in the keymap.

If the thing that you find inconsistent is the difference between `Key_LeftShift` and `ShiftToLayer(N)`, I would say that it's the keymap definition that you have an issue with, not something specific to Qukeys. Note that you could use the following to get more consistency in definitions:
```
#define LayerShift_FUNCTION ShiftToLayer(FUNCTION)
```
…but I wouldn't recommend it.

**Comment by noctuid** [comment]
Sorry for not making myself clear. I like the full Qukey definitions. I'm saying I think it would be nice (if possible) if there was an alternative to `LT`/`MT` that could use any key (like the full definitions) instead of only either a modifier or layer.

**Comment by gedankenexperimenter** [comment]
If I understand you correctly, yes, that would be nice, but there's no practical way to do it, since a `Qukey` object would essentially be storing two `Key` values, so it wouldn't fit in the keymap.

**Comment by gedankenexperimenter** [comment]
Since there's no way to accomplish this (short of a sketch-builder program, which is outside the scope of the plugin), I'm closing this issue.
