### ISSUE TITLE
Incompatibility with Leader Keys

### ISSUE THREAD

**Issue by Llamalland** [keyboardio/Kaleidoscope-Qukeys#46]
Trying to make a leader key as a qukey with alt as the held behaviour broke the leader key functionality.

**Comment by gedankenexperimenter** [comment]
Do you have Qukeys or Leader first in your sketch (either `Kaleidoscope.use()` or `KALEIDOSCOPE_INIT_PLUGINS`)? I expect it to work if Qukeys come first, and fail if Leader comes first.

**Comment by Llamalland** [comment]
No, I saw some of your posts etc. about the place on that topic, so Qukeys is before everything else.

**Comment by Llamalland** [comment]
https://github.com/Llamalland/Keyboardio/blob/master/CurrentSketch.ino

That's my current sketch, with the particular line in my qukeys commented out so I can use the leader sequences instead. Cheers :)

**Comment by gedankenexperimenter** [comment]
I still haven't had a chance to try it out, but I have had an idea? Is it possible that it works when you press _and release_ the qukey(leader) key before you press the first key in the Leader sequence, but not if you roll over from the leader key to the next one?

**Comment by gedankenexperimenter** [comment]
One other thing comes to mind. It's possible that this happens when only if there's a release delay.

**Comment by Llamalland** [comment]
Leader keys only seem to work on release even when they're not a qukey, so that was expected when I changed it into a qukey. Either way, if the leader key was rolled over, I would expect it to get confused with the qukey held functionality (which does seem to work still)

I didn't set anything special for Leader, so it's all default there. For Qukeys, I tried commenting out the release delay, no luck.

**Comment by gedankenexperimenter** [comment]
Qukeys does work in rollover situations; it only produces the alternate keycode if the other key is released first (or the hold timeout is reached).

I'll try to find time to debug this tomorrow, but if I can't, it might be a while before I can do anything about it.

**Comment by Llamalland** [comment]
Ah yeah, I remember about that now. It's just not the reason that I use qukeys, but it is still good to know!

No rush, mate! Thanks :)

**Comment by gedankenexperimenter** [comment]
I think I've got this figured out. The problem was that Leader, unlike most plugins, acts on key _release_ events, not just key press events. Qukeys was aborting processing of key releases after flushing the queue, so the release that would tell Leader to start looking for a sequence would never get through, and it would fail. I've tried it out, and it appears to work, but I don't have time to test it thoroughly. @Llamalland, please try out the fix in #47, and let me know if that works and/or breaks anything else.

@algernon, if this seems to fix things, feel free to merge #47 at your convenience – I might not be around to do it after it's tested. Thanks in advance!

**Comment by algernon** [comment]
#47 makes sense to me, will do a test on my own too tomorrow, but if @Llamalland can test it too, that would be best. Will merge it soon after, if all goes well.

Thank you!

**Comment by Llamalland** [comment]
Will test tomorrow also and report back, cheers!

**Comment by Llamalland** [comment]
Still seems to have the same behaviour. Is there anything I needed to do besides replace the Qukeys.cpp file?

**Comment by gedankenexperimenter** [comment]
Is everything else up to date? Is there only one Kaleidoscope-Qukeys copy that arduino-builder can find? Are you sure your `avr` directory contains (or points to) the correct version of the code?

Unfortunately, there are lots of things that could be a problem with the build. You could try a change to Qukeys.cpp that would be obvious, such as an unconditional `return EventHandlerResult::EVENT_CONSUMED` at the top, just to be sure that the version you're building is to one that you're modifying.

**Comment by Llamalland** [comment]
Found where the offending extra copy was. Fixed, and works great so far!
