### ISSUE TITLE
The use of a qukey in combination with a layer changer

### ISSUE THREAD

**Issue by nevd** [keyboardio/Kaleidoscope-Qukeys#50]
I have mapped pgdown to control using kaleidoscope::Qukey(0,2,0,Key_LeftControl)

I want to be able to use the qukey plus arrow keys which are on a different layer, however this does not appear to work.

Is there a way to allow qukeys to work with layer modifyer keys?

My sketch is https://github.com/nevd/keyboardio

**Comment by gedankenexperimenter** [comment]
I'm sorry I didn't notice this issue until now; I've been too busy for most of the summer to look at Kaleidoscope code.

**Comment by nevd** [comment]
Not a problem, I should have read the documentation more carefully. It was a while ago I put the Qukey into my sketch and I forgot the first number was the layer.
